FROM dustynv/l4t-pytorch:r36.4.0

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg libsm6 libxext6 libxrender-dev \
    libgl1-mesa-glx python3-pip \
    git wget unzip \
    python3-opencv \
    && apt-get clean

# Upgrade pip and install Python packages
COPY requirements_Jetson.txt /app/
RUN pip install --no-cache-dir -r /app/requirements_Jetson.txt \
    --index-url https://pypi.org/simple

# Set working directory
WORKDIR /app
COPY . /app

CMD ["python3", "main_jetson.py"]